"""converted marketcap to BigInt

Revision ID: 14fc519d778b
Revises: 47a86fe74998
Create Date: 2022-03-17 18:58:05.063652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14fc519d778b'
down_revision = '47a86fe74998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
