"""added default value to created_by

Revision ID: 47a86fe74998
Revises: 36fc4e928d2e
Create Date: 2022-03-16 20:02:48.892431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47a86fe74998"
down_revision = "36fc4e928d2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stocks", "created_by", server_default="0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stocks", "created_by", server_default=None)
    # ### end Alembic commands ###
