"""removed unique from name added unique to ticker

Revision ID: 8a9b196c5b7e
Revises: cd80ce8ac50f
Create Date: 2022-03-17 19:07:40.283447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9b196c5b7e'
down_revision = 'cd80ce8ac50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stocks_name_key', 'stocks', type_='unique')
    op.create_unique_constraint(None, 'stocks', ['ticker'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='unique')
    op.create_unique_constraint('stocks_name_key', 'stocks', ['name'])
    # ### end Alembic commands ###
