"""changed PK in portfolio_stocks

Revision ID: a1587b0d4e81
Revises: ad1b0bfc6b53
Create Date: 2022-03-18 23:26:38.821973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1587b0d4e81"
down_revision = "065ba85bac36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_stocks",
        sa.Column("stock_ticker", sa.String(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Float(), nullable=True),
        sa.Column("buy_in", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stock_ticker"], ["stocks.ticker"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("stock_ticker", "portfolio_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portfolio_stocks")
    # ### end Alembic commands ###
