"""try to fix relationship in models try 7

Revision ID: 09daa028df50
Revises: 78d6bb7e259f
Create Date: 2022-03-10 21:45:17.181666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09daa028df50'
down_revision = '78d6bb7e259f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
