"""try to fix relationship in models try 3

Revision ID: 0b9a3117d7a3
Revises: 5c63175d10e0
Create Date: 2022-03-10 21:30:55.521885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9a3117d7a3'
down_revision = '5c63175d10e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
