"""try to fix relationship in models try 10

Revision ID: 0e97bad9936a
Revises: 61a0b390988d
Create Date: 2022-03-10 21:52:32.370807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e97bad9936a'
down_revision = '61a0b390988d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
