"""try to fix relationship in models try 4. Fixed?

Revision ID: 13573a081d61
Revises: 0b9a3117d7a3
Create Date: 2022-03-10 21:38:25.845594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13573a081d61'
down_revision = '0b9a3117d7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
