"""auto-gen tables

Revision ID: 162b90b4a2be
Revises: d02d650d271c
Create Date: 2022-03-08 21:24:10.868629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "162b90b4a2be"
down_revision = "d02d650d271c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("monetary_goal", sa.Float(), nullable=True),
        sa.Column("dividends_goal", sa.Float(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "portfolio_stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("stocks", sa.Column("ticker", sa.String(), nullable=True))
    op.add_column("stocks", sa.Column("yahoo_ticker", sa.String(), nullable=False))
    op.add_column("stocks", sa.Column("exchange", sa.String(length=255), nullable=True))
    op.add_column("stocks", sa.Column("sector", sa.String(length=255), nullable=True))
    op.add_column("stocks", sa.Column("industry", sa.String(length=255), nullable=True))
    op.add_column("stocks", sa.Column("long_business_summary", sa.Text(), nullable=True))
    op.add_column("stocks", sa.Column("country", sa.String(length=255), nullable=True))
    op.add_column("stocks", sa.Column("website", sa.String(length=255), nullable=True))
    op.add_column("stocks", sa.Column("price", sa.Float(), nullable=False))
    op.add_column("stocks", sa.Column("marketcap", sa.Integer(), nullable=True))
    op.add_column("stocks", sa.Column("dividends", sa.Float(), nullable=True))
    op.add_column("stocks", sa.Column("dividend_yield", sa.Float(), nullable=True))
    op.add_column("stocks", sa.Column("ex_dividend_date", sa.Date(), nullable=True))
    op.add_column("stocks", sa.Column("beta", sa.Float(), nullable=True))
    op.add_column("stocks", sa.Column("fifty_two_week_high", sa.Float(), nullable=True))
    op.add_column("stocks", sa.Column("fifty_two_week_low", sa.Float(), nullable=True))
    op.add_column("stocks", sa.Column("fifty_day_avg", sa.Float(), nullable=True))
    op.add_column("stocks", sa.Column("recommendation", sa.String(length=100), nullable=True))
    op.add_column("stocks", sa.Column("total_cash_per_share", sa.BigInteger(), nullable=True))
    op.add_column("stocks", sa.Column("profit_margins", sa.Float(), nullable=True))
    op.add_column("stocks", sa.Column("volume", sa.BigInteger(), nullable=True))
    op.add_column("stocks", sa.Column("status", sa.Integer(), server_default="0", nullable=False))
    op.add_column("stocks", sa.Column("created_by", sa.Integer(), nullable=False))
    op.add_column(
        "stocks", sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column("stocks", sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stocks", "updated_at")
    op.drop_column("stocks", "created_at")
    op.drop_column("stocks", "created_by")
    op.drop_column("stocks", "status")
    op.drop_column("stocks", "volume")
    op.drop_column("stocks", "profit_margins")
    op.drop_column("stocks", "total_cash_per_share")
    op.drop_column("stocks", "recommendation")
    op.drop_column("stocks", "fifty_day_avg")
    op.drop_column("stocks", "fifty_two_week_low")
    op.drop_column("stocks", "fifty_two_week_high")
    op.drop_column("stocks", "beta")
    op.drop_column("stocks", "ex_dividend_date")
    op.drop_column("stocks", "dividend_yield")
    op.drop_column("stocks", "dividends")
    op.drop_column("stocks", "marketcap")
    op.drop_column("stocks", "price")
    op.drop_column("stocks", "website")
    op.drop_column("stocks", "country")
    op.drop_column("stocks", "long_business_summary")
    op.drop_column("stocks", "industry")
    op.drop_column("stocks", "sector")
    op.drop_column("stocks", "exchange")
    op.drop_column("stocks", "yahoo_ticker")
    op.drop_column("stocks", "ticker")
    op.drop_table("portfolio_stocks")
    op.drop_table("portfolios")
    op.drop_table("users")
    # ### end Alembic commands ###
