"""fixed relationship really now

Revision ID: 25ea15425bce
Revises: 5a8f401edf14
Create Date: 2022-03-11 13:42:17.840791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ea15425bce'
down_revision = '5a8f401edf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
