"""trying joints

Revision ID: 2ad74aa92e80
Revises: 25ea15425bce
Create Date: 2022-03-11 14:06:54.961030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2ad74aa92e80"
down_revision = "25ea15425bce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("portfolio_stocks_association_stock_id_fkey", "portfolio_stocks_association", type_="foreignkey")
    op.drop_table("portfolio_stocks")
    op.create_foreign_key(None, "portfolio_stocks_association", "stocks", ["stock_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "portfolio_stocks_association", type_="foreignkey")
    op.create_foreign_key(
        "portfolio_stocks_association_stock_id_fkey",
        "portfolio_stocks_association",
        "portfolio_stocks",
        ["stock_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "portfolio_stocks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("buy_in", postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], name="portfolio_stocks_stock_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="portfolio_stocks_pkey"),
    )
    # ### end Alembic commands ###
