"""changed nullable in count+buy_in in portoflio_stocks

Revision ID: 3e330bbbc609
Revises: a2bed4b6e8ca
Create Date: 2022-03-10 20:17:31.134039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e330bbbc609'
down_revision = 'a2bed4b6e8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_stocks', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('portfolio_stocks', 'buy_in',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_stocks', 'buy_in',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('portfolio_stocks', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
