"""try to fix relationship in models

Revision ID: 4c0b65a5b1db
Revises: 3e330bbbc609
Create Date: 2022-03-10 21:28:14.682480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0b65a5b1db'
down_revision = '3e330bbbc609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
