"""fixed relationship?

Revision ID: 5a8f401edf14
Revises: 85d0a4d2c522
Create Date: 2022-03-11 13:36:07.324816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8f401edf14'
down_revision = '85d0a4d2c522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'stocks', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='unique')
    op.alter_column('stocks', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
