"""try to fix relationship in models try 2

Revision ID: 5c63175d10e0
Revises: 4c0b65a5b1db
Create Date: 2022-03-10 21:29:31.491760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c63175d10e0'
down_revision = '4c0b65a5b1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
