"""try to fix relationship in models try 9

Revision ID: 61a0b390988d
Revises: e5f3c71156ef
Create Date: 2022-03-10 21:47:06.560304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a0b390988d'
down_revision = 'e5f3c71156ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
