"""try to fix relationship in models try 12

Revision ID: 69512fb7cb78
Revises: b1fa6769cc08
Create Date: 2022-03-10 22:26:44.341141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69512fb7cb78'
down_revision = 'b1fa6769cc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
