"""added columns in portfolio stocks

Revision ID: 74e634ec4f9d
Revises: 162b90b4a2be
Create Date: 2022-03-10 20:05:29.429160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e634ec4f9d'
down_revision = '162b90b4a2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
