"""try to fix relationship in models try 5

Revision ID: 7685ee0d17e1
Revises: 13573a081d61
Create Date: 2022-03-10 21:42:55.843364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7685ee0d17e1'
down_revision = '13573a081d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
