"""try to fix relationship in models try 6

Revision ID: 78d6bb7e259f
Revises: 7685ee0d17e1
Create Date: 2022-03-10 21:44:18.858204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d6bb7e259f'
down_revision = '7685ee0d17e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
