"""fixing portfolios try1

Revision ID: 85d0a4d2c522
Revises: a1575889bd6c
Create Date: 2022-03-11 13:17:08.922912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85d0a4d2c522"
down_revision = "a1575889bd6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_stocks_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("buy_in", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stock_id"], ["portfolio_stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("portfolio_stocks_portfolio_id_fkey", "portfolio_stocks", type_="foreignkey")
    op.drop_column("portfolio_stocks", "portfolio_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("portfolio_stocks", sa.Column("portfolio_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        "portfolio_stocks_portfolio_id_fkey",
        "portfolio_stocks",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("portfolio_stocks_association")
    # ### end Alembic commands ###
