"""renamed tables

Revision ID: a1575889bd6c
Revises: 69512fb7cb78
Create Date: 2022-03-11 13:07:28.019272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1575889bd6c'
down_revision = '69512fb7cb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
