"""changed PK in portfolio_stocks

Revision ID: a1587b0d4e81
Revises: ad1b0bfc6b53
Create Date: 2022-03-18 23:26:38.821973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1587b0d4e81'
down_revision = 'ad1b0bfc6b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_stocks',
    sa.Column('stock_ticker', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Float(), nullable=True),
    sa.Column('buy_in', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_ticker', 'portfolio_id')
    )
    op.drop_index('ix_temp_stocks_index', table_name='temp_stocks')
    op.drop_table('temp_stocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_stocks',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('yahoo_ticker', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sector', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('long_business_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('marketcap', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dividends', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividend_yield', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ex_dividend_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('beta', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_day_avg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_cash_per_share', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('profit_margins', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_temp_stocks_index', 'temp_stocks', ['index'], unique=False)
    op.drop_table('portfolio_stocks')
    # ### end Alembic commands ###
