"""added columns in portfolio stocks

Revision ID: a2bed4b6e8ca
Revises: 74e634ec4f9d
Create Date: 2022-03-10 20:06:32.739783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2bed4b6e8ca'
down_revision = '74e634ec4f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_stocks', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('portfolio_stocks', sa.Column('buy_in', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_stocks', 'buy_in')
    op.drop_column('portfolio_stocks', 'count')
    # ### end Alembic commands ###
