"""moved FK in portfolio_stocks to ticker

Revision ID: ad1b0bfc6b53
Revises: 8a9b196c5b7e
Create Date: 2022-03-17 19:17:22.888020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad1b0bfc6b53"
down_revision = "8a9b196c5b7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("portfolio_stocks", sa.Column("stock_ticker", sa.String(), nullable=True))
    op.drop_constraint("portfolio_stocks_stock_id_fkey", "portfolio_stocks", type_="foreignkey")
    op.create_foreign_key(None, "portfolio_stocks", "stocks", ["stock_ticker"], ["ticker"], ondelete="CASCADE")
    op.drop_column("portfolio_stocks", "stock_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("portfolio_stocks", sa.Column("stock_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "portfolio_stocks", type_="foreignkey")
    op.create_foreign_key(
        "portfolio_stocks_stock_id_fkey", "portfolio_stocks", "stocks", ["stock_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("portfolio_stocks", "stock_ticker")
    # ### end Alembic commands ###
