"""try to fix relationship in models try 11

Revision ID: b1fa6769cc08
Revises: 0e97bad9936a
Create Date: 2022-03-10 22:03:06.187742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fa6769cc08'
down_revision = '0e97bad9936a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
