"""converted marketcap to BigInt2

Revision ID: cd80ce8ac50f
Revises: 14fc519d778b
Create Date: 2022-03-17 18:58:44.164456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd80ce8ac50f"
down_revision = "14fc519d778b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stocks", "marketcap", existing_type=sa.BigInteger(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
