"""the way it was

Revision ID: ded89bc7e45c
Revises: 2ad74aa92e80
Create Date: 2022-03-11 15:28:47.955423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded89bc7e45c'
down_revision = '2ad74aa92e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
