"""try to fix relationship in models try 8

Revision ID: e5f3c71156ef
Revises: 09daa028df50
Create Date: 2022-03-10 21:46:27.629222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f3c71156ef'
down_revision = '09daa028df50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
